name: Hello World and Flutter Web Build

on:
  repository_dispatch:
    types:
      - hello-world

jobs:
  build-flutter-web:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout Code from Another Repository
        uses: actions/checkout@v2
        with:
          repository: MohamedAshraf701/expensify
          ref: master  
          token: ${{ secrets.TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Build Flutter Web
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /expensifybuild/
        
      
      - name: Trigger Hello World Workflow
        env:
          TARGET_REPO_OWNER: MohamedAshraf701  # Replace with the owner of the target repository
          TARGET_REPO_NAME: expensifybuild   # Replace with the name of the target repository
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/dispatches" \
            -d '{"event_type": "sync-code"}'
